import Head from 'next/head'
import RowSlides from "@/domain/home/rowSlides";
import Slide1 from "@/static/images/image 29.svg"
import Slide2 from "@/static/images/image 28.svg"
import DiscountProducts from "@/domain/home/discountProducts";
import BestSellProduct from "@/domain/home/bestSellProducts";
import FavCategory from "@/domain/home/favCategory";
import AmazingOffer from "@/domain/home/amazingOffer";
import RowSlidesType from "@/domain/home/rowSlidesType";
import MobileApp from "@/domain/home/mobileApp";

const rowSlides2=[Slide2,Slide1]
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
    <DiscountProducts/>
      <RowSlides slides={rowSlides2}/>
    <FavCategory/>
    <AmazingOffer/>
    <BestSellProduct/>
    <RowSlidesType/>
    <MobileApp/>
      </main>
    </>
  )
}
